=== rgeyer/rs_selfservice/json/full/schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema",
  "title": "RightScale Self Service Vending Machine Product",
  "type":"object",
  "required": ["name", "resources"],
  "properties":{
    "id": {
      "type":"string",
      "description": "An optional unique ID of the product.  Ignored for create operations and present in the schema as a placeholder for the peristence mechanism I.E. MongoDB object id"
    },
    "name": { "type":"string" },
    "icon_filename": {
      "type":"string",
      "description": "The filename of an icon in the icon directory of the Vending Machine application"
    },
    "launch_servers": { "type":"boolean" },
    "version": {
      "type":"string",
      "pattern":"^[0-9]+\\.[0-9]+\\.[0-9]+$",
      "description": "An optional DB schema version.  This is a semantic version number and it identifies the version of the object schema as stored in a NoSQL database."
    },
    "resources": {
      "type":"array",
      "items":
      {
        "type": "object",
        "anyOf": [
          { "$ref": "#/definitions/deployment" },
          { "$ref": "#/definitions/input" },
          { "$ref": "#/definitions/instance" },
          { "$ref": "#/definitions/security_group" },
          { "$ref": "#/definitions/server" },
          { "$ref": "#/definitions/server_array" },
          { "$ref": "#/definitions/elasticity_params" },
          { "$ref": "#/definitions/server_template" },
          { "$ref": "#/definitions/text_rsss_input" },
          { "$ref": "#/definitions/cloud_rsss_input" },
          { "$ref": "#/definitions/instance_type_rsss_input" },
          { "$ref": "#/definitions/alert_spec" }
        ]
      }
    }
  },
  "definitions": {
    "deployment": {
      "type":"object",
      "required": ["id", "resource_type", "name", "servers"],
      "properties":{
        "id": { "type":"string" },
        "resource_type": { "enum": ["deployment"] },
        "name": { "type": "string" },
        "server_tag_scope": { "enum": ["deployment","account"] },
        "inputs": {
          "type":"array",
          "items":
          {
            "type":"object",
            "oneOf": [
              { "$ref": "#/definitions/input" },
              { "$ref": "#/definitions/input_relationship" }
            ]
          }
        },
        "servers": {
          "type":"array",
          "items":
          {
            "type":"object",
            "anyOf": [
              { "$ref": "#/definitions/server" },
              { "$ref": "#/definitions/server_relationship" }
            ]
          }
        },
        "server_arrays": {
          "type": "array",
          "items": {
            "type":"object",
            "anyOf": [
              { "$ref": "#/definitions/server_array" },
              { "$ref": "#/definitions/server_array_relationship" }
            ]
          }
        }
      }
    },
    "alert_spec": {
      "type": "object",
      "required": ["id", "resource_type", "name", "condition", "duration", "file", "name", "threshold", "variable"],
      "properties": {
        "id": { "type":"string" },
        "resource_type": { "enum": ["alert_spec"] },
        "name": { "type": "string" },
        "condition": {
          "enum": [">",">=","<","<=","==","!="]
        },
        "description": { "type": "string" },
        "duration": { "type": "string" },
        "escalation_name": { "type": "string" },
        "file": { "type": "string" },
        "threshold": { "type": "string" },
        "variable": { "type": "string" },
        "vote_tag": { "type": "string" },
        "vote_type": { "enum": ["grow","shrink"] }
      }
    },
    "server_array": {
      "type": "object",
      "required": [
        "id",
        "resource_type",
        "array_type",
        "elasticity_params",
        "instance",
        "name"
      ],
      "properties":{
        "id": { "type":"string" },
        "resource_type": { "enum": ["server_array"] },
        "array_type": { "enum": ["alert","queue"] },
        "description": { "type": "string" },
        "elasticity_params": {
          "type": "object",
          "anyOf": [
            { "$ref": "#/definitions/elasticity_params" },
            { "$ref": "#/definitions/elasticity_params_relationship" }
          ]
        },
        "instance": {
          "type": "object",
          "anyOf": [
            { "$ref": "#/definitions/instance" },
            { "$ref": "#/definitions/instance_relationship" }
          ]
        },
        "name": { "type": "string" },
        "optimized": { "type": "boolean" },
        "state": { "enum": ["enabled","disabled"], "default": "disabled" },
        "alert_specs": {
          "type": "array",
          "items": {
            "anyOf": [
              { "$ref": "#/definitions/alert_spec" },
              { "$ref": "#/definitions/alert_spec_relationship" }
            ]
          }
        }
      }
    },
    "elasticity_params": {
      "type": "object",
      "required": ["id","resource_type","bounds","pacing"],
      "properties": {
        "id": { "type": "string" },
        "resource_type": { "enum": ["elasticity_params"] },
        "bounds": {
          "type": "object",
          "required": ["min_count","max_count"],
          "properties": {
            "max_count": { "type": "string" },
            "min_count": { "type": "string" }
          }
        },
        "pacing": {
          "type": "object",
          "required": ["resize_calm_time","resize_down_by","resize_up_by"],
          "properties": {
            "resize_calm_time": { "type": "string" },
            "resize_down_by": { "type": "string" },
            "resize_up_by": { "type": "string" }
          }
        },
        "alert_specific_params": {
          "type": "object",
          "properties": {
            "decision_threshold": { "type": "string" },
            "voters_tag_predicate": { "type": "string" }
          }
        },
        "queue_specific_params": {
          "type": "object",
          "properties": {
            "collect_audit_entries": { "type": "string" },
            "item_age": {
              "type": "object",
              "properties": {
                "algorithm": { "enum": ["max_10","avg_10"] },
                "max_age": { "type": "string" },
                "regexp": { "type": "string" }
              }
            },
            "queue_size": {
              "type": "object",
              "properties": {
                "items_per_instance": { "type": "string" }
              }
            }
          }
        },
        "schedule": {
          "type": "array",
          "items": {
            "type": "object",
            "required": ["day","max_count","min_count","time"],
            "properties": {
              "day": { "enum": ["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"] },
              "max_count": { "type": "string" },
              "min_count": { "type": "string" },
              "time": { "type": "string", "pattern": "^\\d\\d:\\d\\d$" }
            }
          }
        }
      }
    },
    "server": {
      "type": "object",
      "required": ["id","resource_type","name","instance"],
      "properties": {
        "id": { "type": "string" },
        "resource_type": { "enum": ["server"] },
        "name": { "type":"string" },
        "instance": {
          "type": "object",
          "anyOf": [
            { "$ref": "#/definitions/instance" },
            { "$ref": "#/definitions/instance_relationship" }
          ]
        },
        "alert_specs": {
          "type": "array",
          "items": {
            "anyOf": [
              { "$ref": "#/definitions/alert_spec" },
              { "$ref": "#/definitions/alert_spec_relationship" }
            ]
          }
        }
      }
    },
    "instance": {
      "type": "object",
      "required": ["id","resource_type","cloud_href","server_template"],
      "properties": {
        "id": { "type": "string" },
        "resource_type": { "enum": ["instance"] },
        "cloud_href": {
          "type": "object",
          "oneOf": [
            { "$ref": "#/definitions/cloud_rsss_input_relationship" }
          ]
        },
        "datacenter_href": {
          "description": "When set to a datacenter_rsss_input with more than one datacenter href, as a child of a server_array, the server_array datacenter_policy will be set to be evenly weighted across the specified datacenter_hrefs",
          "type": "object",
          "oneOf": [
            { "$ref": "#/definitions/datacenter_rsss_input_relationship" }
          ]
        },
        "inputs": {
          "type": "array",
          "items": {
            "anyOf": [
              { "$ref": "#/definitions/input" },
              { "$ref": "#/definitions/input_relationship" }
            ]
          }
        },
        "instance_type_href": {
          "type": "object",
          "oneOf": [
            { "$ref": "#/definitions/instance_type_rsss_input_relationship" }
          ]
        },
        "security_groups": {
          "type": "array",
          "items": {
            "anyOf": [
              { "$ref": "#/definitions/security_group" },
              { "$ref": "#/definitions/security_group_relationship" }
            ]
          }
        },
        "server_template": {
          "type": "object",
          "anyOf": [
            { "$ref": "#/definitions/security_group" },
            { "$ref": "#/definitions/security_group_relationship" }
          ]
        }
      }
    },
    "input": {
      "type":"object",
      "required": ["id","resource_type","name","value"],
      "properties": {
        "id": { "type": "string" },
        "resource_type": { "enum": ["input"] },
        "name": { "type":"string" },
        "value": {
          "type":"string",
          "pattern":"^(text|key|cred|array|env):.*"
        }
      }
    },
    "security_group": {
      "type":"object",
      "required": ["id","resource_type","cloud_href","name"],
      "properties":{
        "id": { "type":"string" },
        "resource_type": { "enum": ["security_group"] },
        "cloud_href": {
          "type": "object",
          "oneOf": [
            { "$ref": "#/definitions/cloud_rsss_input_relationship" }
          ]
        },
        "description": { "type":"string" },
        "name": { "type":"string" },
        "security_group_rules": {
          "type": "array",
          "items": {
            "anyOf": [
              { "$ref": "#/definitions/security_group_rule" },
              { "$ref": "#/definitions/security_group_rule_relationship" }
            ]
          }
        }
      }
    },
    "security_group_rule": {
      "type": "object",
      "required": ["id","resource_type","protocol","protocol_details","source_type"],
      "properties": {
        "id": { "type": "string" },
        "resource_type": { "enum": ["security_group_rule"] },
        "cidr_ips": { "type": "string" },
        "ingress_group": { "$ref": "#/definitions/security_group_relationship" },
        "protocol": { "enum": ["tcp","udp","icmp"] },
        "protocol_details": {
          "type": "object",
          "properties": {
            "end_port": { "type": "string" },
            "icmp_code": { "type": "string" },
            "icmp_type": { "type": "string" },
            "start_port": { "type": "string" }
          }
        },
        "source_type": {
          "emum": ["cidr_ips","group"]
        }
      }
    },
    "text_rsss_input" : {
      "type":"object",
      "required":["id","resource_type","type","default_value","input_name","display_name"],
      "properties":{
        "id": { "type":"string" },
        "resource_type": { "enum": "text_rsss_input" },
        "type": { "enum": ["text"] },
        "default_value": { "type":"string" },
        "input_name": { "type":"string" },
        "display_name": { "type":"string" },
        "description": { "type":"string" },
        "display": { "type": "boolean", "default": true }
      }
    },
    "cloud_rsss_input" : {
      "type":"object",
      "required":["id","resource_type","type","default_value","input_name","display_name"],
      "properties":{
        "id": { "type":"string" },
        "resource_type": { "enum": "cloud_rsss_input" },
        "type": { "enum": ["cloud"] },
        "default_value": { "type":"string" },
        "input_name": { "type":"string" },
        "display_name": { "type":"string" },
        "description": { "type":"string" },
        "display": { "type": "boolean", "default": true }
      }
    },
    "instance_type_rsss_input" : {
      "type":"object",
      "required":["id","resource_type","type","cloud_rsss_input","default_value","input_name","display_name"],
      "properties":{
        "id": { "type":"string" },
        "resource_type": { "enum": "instance_type_rsss_input" },
        "type": { "enum": ["instance_type"] },
        "cloud_rsss_input": { "$ref": "#/definitions/cloud_rsss_input_relationship" },
        "default_value": {
          "type":"array",
          "items": {
            "type":"object",
            "oneOf": [
              { "$ref": "#/definitions/cloud_to_resource_href_hash" }
            ]
          }
        },
        "input_name": { "type":"string" },
        "display_name": { "type":"string" },
        "description": { "type":"string" },
        "display": { "type": "boolean", "default": true }
      }
    },
    "datacenter_rsss_input" : {
      "type":"object",
      "required":["id","resource_type","type","cloud_rsss_input","default_value","input_name","display_name"],
      "properties":{
        "id": { "type":"string" },
        "resource_type": { "enum": "datacenter_rsss_input" },
        "type": { "enum": ["datacenter"] },
        "cloud_rsss_input": { "$ref": "#/definitions/cloud_rsss_input_relationship" },
        "default_value": {
          "type":"array",
          "items": {
            "type":"object",
            "oneOf": [
              { "$ref": "#/definitions/cloud_to_resource_href_hash" }
            ]
          }
        },
        "input_name": { "type":"string" },
        "display_name": { "type":"string" },
        "description": { "type":"string" },
        "display": { "type": "boolean", "default": true }
      }
    },
    "cloud_to_resource_href_hash": {
      "type": "object",
      "required": ["cloud_href","resource_hrefs"],
      "properties": {
        "cloud_href": { "type": "string" },
        "resource_hrefs": {
          "type": "array",
          "minItems": 1,
          "items": {
            "type": "string",
            "pattern": "^\\/api[a-zA-Z_0-9\\/]+$"
          }
        }
      }
    },
    "input_relationship": {
      "type":"object",
      "required": ["id", "ref"],
      "properties":{
        "id": { "type":"string" },
        "ref": { "enum": ["input"] }
      }
    },
    "server_relationship": {
      "type":"object",
      "required": ["id", "ref"],
      "properties":{
        "id": { "type":"string" },
        "ref": { "enum": ["server"] }
      }
    },
    "server_array_relationship": {
      "type":"object",
      "required": ["id", "ref"],
      "properties":{
        "id": { "type":"string" },
        "ref": { "enum": ["server_array"] }
      }
    },
    "elasticity_params_relationship": {
      "type":"object",
      "required": ["id", "ref"],
      "properties":{
        "id": { "type":"string" },
        "ref": { "enum": ["elasticity_params"] }
      }
    },
    "instance_relationship": {
      "type":"object",
      "required": ["id", "ref"],
      "properties":{
        "id": { "type":"string" },
        "ref": { "enum": ["instance"] }
      }
    },
    "alert_spec_relationship": {
      "type":"object",
      "required": ["id", "ref"],
      "properties":{
        "id": { "type":"string" },
        "ref": { "enum": ["alert_spec"] }
      }
    },
    "cloud_rsss_input_relationship": {
      "type":"object",
      "required": ["id", "ref"],
      "properties":{
        "id": { "type":"string" },
        "ref": { "enum": ["cloud_rsss_input"] }
      }
    },
    "instance_type_rsss_input_relationship": {
      "type":"object",
      "required": ["id", "ref"],
      "properties":{
        "id": { "type":"string" },
        "ref": { "enum": ["instance_type_rsss_input"] }
      }
    },
    "datacenter_rsss_input_relationship": {
      "type":"object",
      "required": ["id", "ref"],
      "properties":{
        "id": { "type":"string" },
        "ref": { "enum": ["datacenter_rsss_input"] }
      }
    },
    "text_rsss_input_relationship": {
      "type":"object",
      "required": ["id", "ref"],
      "properties":{
        "id": { "type":"string" },
        "ref": { "enum": ["text_rsss_input"] }
      }
    },
    "security_group_relationship": {
      "type":"object",
      "required": ["id", "ref"],
      "properties":{
        "id": { "type":"string" },
        "ref": { "enum": ["security_group"] }
      }
    },
    "security_group_rule_relationship": {
      "type":"object",
      "required": ["id", "ref"],
      "properties":{
        "id": { "type":"string" },
        "ref": { "enum": ["security_group_rule"] }
      }
    }
  }
}

=== rgeyer/rs_selfservice/products/3tier-windows.json
{
  "version": "1.0.0",
  "name": "Windows 3-Tier",
  "icon_filename": "windows.png",
  "launch_servers": false,
  "resources": [
    {
      "id": "haz_logging",
      "resource_type": "select_product_input",
      "options": ["true","false"],
      "default_value": ["true"],
      "input_name": "haz_logging",
      "display_name": "Log to rsyslog?",
      "description": "",
      "advanced": true
    },
    {
      "id": "mssql_witness_template",
      "resource_type": "server_template",
      "name": "Microsoft SQL Server Witness - Beta (v13.4)",
      "revision": "16",
      "publication_id": "53470"
    },
    {
      "id": "mssql_db_template",
      "resource_type": "server_template",
      "name": "Database Manager for Microsoft SQL Server (v13.4)",
      "revision": "93",
      "publication_id": "53469",
      "depends": {
        "ref": "text_product_input",
        "id": "db_tier_type",
        "value": ["mssql"]
      }
    },
    {
      "id": "iis_app_template",
      "resource_type": "server_template",
      "name": "Microsoft IIS App Server (v13.4)",
      "revision": "76",
      "publication_id": "52637"
    },
    {
      "id": "ad_template",
      "resource_type": "server_template",
      "name": "Microsoft Active Directory (v13.4)",
      "revision": "62",
      "publication_id": "52660"
    }
  ]
}

=== rgeyer/rs_selfservice/products/baselinux.json
{
  "version": "1.0.0",
  "name": "Base Linux",
  "icon_filename": "redhat.png",
  "launch_servers": true,
  "resources": [
    {
      "id": "deployment_name",
      "resource_type": "text_product_input",
      "default_value": "Base",
      "input_name": "deployment_name",
      "display_name": "Deployment Name",
      "description": "The deployment name"
    },
    {
      "id": "cloud",
      "resource_type": "cloud_product_input",
      "default_value": "/api/clouds/1",
      "input_name": "cloud",
      "display_name": "Cloud",
      "description": "The target cloud for the servers"
    },
    {
      "id": "instance_count",
      "resource_type": "text_product_input",
      "default_value": "1",
      "input_name": "instance_count",
      "display_name": "Count",
      "description": "The number of instances to create and launch"
    },
    {
      "id": "instance_type",
      "resource_type": "instance_type_product_input",
      "cloud_product_input": { "ref": "cloud_product_input", "id": "cloud" },
      "default_value": [
        {
          "cloud_href": "/api/clouds/1",
          "resource_hrefs": ["/api/clouds/1/instance_types/CQQV62T389R32"]
        },
        {
          "cloud_href": "/api/clouds/2",
          "resource_hrefs": ["/api/clouds/2/instance_types/DSPQL6A26DJIA"]
        }
      ],
      "input_name": "instance_type",
      "display_name": "Instance Type",
      "description": "The instance type for the servers"
    },
    {
      "id": "Deployment",
      "resource_type": "deployment",
      "name": { "ref": "text_product_input", "id": "deployment_name" },
      "inputs": [],
      "servers": [
        {
          "id": "BaseServer",
          "resource_type": "server",
          "name_prefix": "base",
          "optimized": false,
          "count": { "ref": "text_product_input", "id": "instance_count" },
          "instance": {
            "id": "BaseInstance",
            "resource_type": "instance",
            "cloud_href": { "ref": "cloud_product_input", "id": "cloud" },
            "instance_type_href": { "ref": "instance_type_product_input", "id": "instance_type" },
            "security_groups": [
              { "ref": "security_group", "id": "DefaultSecurityGroup" }
            ],
            "server_template": { "ref": "server_template", "id": "BaseServerTemplate" }
          }
        }
      ],
      "server_arrays": []
    },
    {
      "id": "DefaultSecurityGroup",
      "resource_type": "security_group",
      "name": "base-default",
      "description": "Base Linux",
      "cloud_href": { "ref": "cloud_product_input", "id": "cloud" },
      "security_group_rules": [
        {
          "id": "SshIngressSecurityGroupRule",
          "resource_type": "security_group_rule",
          "protocol": "tcp",
          "cidr_ips": "0.0.0.0\/0",
          "source_type": "cidr_ips",
          "protocol_details": {
            "end_port": "22",
            "start_port": "22"
          }
        },
        {
          "id": "HttpIngressSecurityGroupRule",
          "resource_type": "security_group_rule",
          "protocol": "tcp",
          "cidr_ips": "0.0.0.0\/0",
          "source_type": "cidr_ips",
          "protocol_details": {
            "end_port": "80",
            "start_port": "80"
          }
        }
      ]
    },
    {
      "id": "BaseServerTemplate",
      "resource_type": "server_template",
      "name": "Base ServerTemplate for Linux (v13.2.1)",
      "revision": "121",
      "publication_id": "46542"
    }
  ]
}

=== rgeyer/rs_selfservice/products/3tier-bursting.json
{
  "version": "1.0.0",
  "name": "3-Tier with Cloud Bursting",
  "icon_filename": "apache.png",
  "launch_servers": false,
  "resources": [
    {
      "id": "deployment_name",
      "resource_type": "text_product_input",
      "default_value": "3-Tier with Cloud Bursting",
      "input_name": "deployment_name",
      "display_name": "Deployment Name",
      "description": "The deployment name"
    },
    {
      "id": "cloud_1",
      "resource_type": "cloud_product_input",
      "default_value": "/api/clouds/1",
      "input_name": "cloud_1",
      "display_name": "Cloud",
      "description": "The cloud where your application runs steady-state"
    },
    {
      "id": "cloud_2",
      "resource_type": "cloud_product_input",
      "default_value": "/api/clouds/2",
      "input_name": "cloud_2",
      "display_name": "Burst Cloud",
      "description": "The cloud your application will burst into for additional capacity"
    },
    {
      "id": "app_tier_type",
      "resource_type": "select_product_input",
      "options": ["php","python","java","ruby"],
      "default_value": ["php"],
      "input_name": "app_tier_type",
      "display_name": "Application Tier Technology",
      "description": "The type of app server to use"
    },
    {
      "id": "db_tier_type",
      "resource_type": "select_product_input",
      "options": ["pgsql","mysql"],
      "default_value": ["mysql"],
      "input_name": "db_tier_type",
      "display_name": "Database Tier Technology",
      "description": "The type of database to use"
    },
    {
      "id": "haz_logging",
      "resource_type": "select_product_input",
      "options": ["true","false"],
      "default_value": ["true"],
      "input_name": "haz_logging",
      "display_name": "Log to rsyslog?",
      "description": "",
      "advanced": true
    },
    {
      "id": "haz_caching",
      "resource_type": "select_product_input",
      "options": ["true","false"],
      "default_value": ["true"],
      "input_name": "haz_caching",
      "display_name": "Enable Memcached?",
      "description": "",
      "advanced": true
    },
    {
      "id": "deployment",
      "resource_type": "deployment",
      "name": { "ref": "text_product_input", "id": "deployment_name" }
    },
    {
      "id": "rsyslog_template",
      "resource_type": "server_template",
      "name": "Logging with rsyslog Beta (v13.4)",
      "revision": "48",
      "publication_id": "52716"
    },
    {
      "id": "memcached_template",
      "resource_type": "server_template",
      "name": "Memcached Server Beta (v13.4)",
      "revision": "49",
      "publication_id": "52715"
    },
    {
      "id": "pgsql_db_template",
      "resource_type": "server_template",
      "name": "Database Manager for PostgreSQL 9.1 Beta (v13.4)",
      "revision": "56",
      "publication_id": "52713",
      "depends": {
        "ref": "text_product_input",
        "id": "db_tier_type",
        "value": ["pgsql"]
      }
    },
    {
      "id": "mysql_db_template",
      "resource_type": "server_template",
      "name": "Database Manager for MySQL 5.5 (v13.4)",
      "revision": "125",
      "publication_id": "52712",
      "depends": {
        "ref": "text_product_input",
        "id": "db_tier_type",
        "value": ["mysql"]
      }
    },
    {
      "id": "python_app_template",
      "resource_type": "server_template",
      "name": "Django App Server Beta (v13.4)",
      "revision": "60",
      "publication_id": "52709",
      "depends": {
        "ref": "text_product_input",
        "id": "app_tier_type",
        "value": ["python"]
      }
    },
    {
      "id": "java_app_template",
      "resource_type": "server_template",
      "name": "Tomcat7 App Server Beta (v13.4)",
      "revision": "63",
      "publication_id": "52708",
      "depends": {
        "ref": "text_product_input",
        "id": "app_tier_type",
        "value": ["java"]
      }
    },
    {
      "id": "ruby_app_template",
      "resource_type": "server_template",
      "name": "Passenger-Rails with Ruby 1.9 App Server (v13.4)",
      "revision": "14",
      "publication_id": "52706",
      "depends": {
        "ref": "text_product_input",
        "id": "app_tier_type",
        "value": ["ruby"]
      }
    },
    {
      "id": "php_app_template",
      "resource_type": "server_template",
      "name": "PHP App Server (v13.4)",
      "revision": "176",
      "publication_id": "52704",
      "depends": {
        "ref": "text_product_input",
        "id": "app_tier_type",
        "value": ["php"]
      }
    },
    {
      "id": "haproxy_template",
      "resource_type": "server_template",
      "name": "Load Balancer with HAProxy (v13.4)",
      "revision": "155",
      "publication_id": "52702"
    }
  ]
}
